# -*- coding: utf-8 -*-
"""entertainer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SR5kAHfwOjFW_loBbcIBw5xSQfCeJUqG
"""

import numpy as np
import pandas as pd
data=pd.read_excel('Entertainer.xlsx')
data

data.isnull().any()

# Fill null values with 0 in the specified column
data['Year of First Oscar/Grammy/Emmy'] = data['Year of First Oscar/Grammy/Emmy'].fillna(0)
data['Year of Death'] = data['Year of Death'].fillna(0)

data.isnull().any()

# Dictionary to rename columns
new_column_names = {
    'Year of Breakthrough/#1 Hit/Award Nomination': 'Year of Breakthrough',
    'Breakthrough Name': 'Breakthrough Name',
    'Year of First Oscar/Grammy/Emmy': 'First Oscar/Grammy/Emmy Year',
    'Gender (traditional)': 'Gender',
    'Birth Year': 'Birth Year',
    'Year of Last Major Work (arguable)': 'Last Major Work Year',
    'Year of Death': 'Year of Death'
}

# Renaming the columns
data.rename(columns=new_column_names, inplace=True)

data.isnull().any()

#Gender Distribution in Entertainment
import matplotlib.pyplot as plt
plt.figure(figsize=(8, 6))
data['Gender'].value_counts().plot.pie(autopct='%1.1f%%', startangle=90, colors=['skyblue', 'lightgreen'])
plt.title('Gender Distribution in Entertainment')
plt.ylabel('')
plt.show()

# 2. Birth Year Distribution
import seaborn as sns
plt.figure(figsize=(8, 6))
sns.histplot(data['Birth Year'].dropna(), bins=30, kde=True)
plt.title('Birth Year Distribution')
plt.xlabel('Birth Year')
plt.ylabel('Frequency')
plt.show()

# 3. Breakthrough Year Distribution
plt.figure(figsize=(8, 6))
sns.histplot(data['Year of Breakthrough'].dropna(), bins=30, kde=True)
plt.title('Breakthrough Year Distribution')
plt.xlabel('Year of Breakthrough')
plt.ylabel('Frequency')
plt.show()

# 4. Year of First Major Award (Oscar/Grammy/Emmy)
plt.figure(figsize=(8, 6))
sns.lineplot(data=data['First Oscar/Grammy/Emmy Year'].dropna().value_counts().sort_index())
plt.title('Year of First Major Award')
plt.xlabel('Year')
plt.ylabel('Number of Awards')
plt.show()

# 8. Active Years in Entertainment
data['Active Years'] = data['Last Major Work Year'] - data['Birth Year']
plt.figure(figsize=(8, 6))
sns.histplot(data['Active Years'].dropna(), bins=30, kde=True)
plt.title('Active Years in Entertainment')
plt.xlabel('Years')
plt.ylabel('Frequency')
plt.show()

#Career Longevity (Scatter Plot)
plt.figure(figsize=(8, 6))
sns.scatterplot(x=data['Birth Year'], y=data['Last Major Work Year'])
plt.title('Career Longevity')
plt.xlabel('Birth Year')
plt

#The histogram shows the distribution of career spans (years between breakthrough and last major work year), providing insights into typical career durations.
python

data['Career Span'] = data['Last Major Work Year'] - data['Year of Breakthrough']
plt.figure(figsize=(8, 6))
sns.histplot(data['Career Span'].dropna(), bins=30, kde=True)
plt.title('Career Span')
plt.xlabel('Years')
plt.ylabel('Frequency')
plt.show()

#Insight: This stacked bar chart displays gender distribution by breakthrough year, revealing if there are gender disparities in when breakthroughs occur.
python

plt.figure(figsize=(12, 8))
gender_by_breakthrough_year = data.pivot_table(index='Year of Breakthrough', columns='Gender', aggfunc='size', fill_value=0)
gender_by_breakthrough_year.plot(kind='bar', stacked=True, color=['skyblue', 'lightgreen'])
plt.title('Gender Distribution by Breakthrough Year')
plt.xlabel('Year of Breakthrough')
plt.ylabel('Number of Entertainers')
plt.show()

